# Generated by Django 5.2.5 on 2025-08-16 04:43

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=144)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=courses.models.image_upload_path)),
                ('access', models.CharField(choices=[('any', 'Anyone'), ('email', 'Email Required')], default='any', max_length=7)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('soon', 'Coming Soon'), ('publish', 'Published')], default='draft', max_length=7)),
            ],
        ),
    ]
