# Generated by Django 5.2.5 on 2025-08-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug_id',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='slug_id',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
