# Generated by Django 5.2.5 on 2025-08-17 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_slug_id_lesson_slug_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
