# Generated by Django 5.2.5 on 2025-08-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_thumbnail_lesson_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug_id',
            field=models.CharField(blank=True, db_index=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug_id',
            field=models.CharField(blank=True, db_index=True, max_length=160, null=True),
        ),
    ]
